# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: localhost
  become: yes
  vars:
      nsx_manager: '10.114.200.41'
      nsx_username: 'admin'
      nsx_password: 'myPassword1!myPassword1!'
      validate_certs: 'false'
  tasks:
    - name: Segment ANS-3Tier
      nsxt_policy_segment:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-3Tier"
        transport_zone_display_name: "Overlay-TZ"
        tier1_id: "ANS-VMW-T1"
        advanced_config:
          connectivity: "ON"
        subnets:
          - gateway_address: "192.40.10.1/24"

    - name: Segment ANS-Client
      nsxt_policy_segment:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-Client"
        transport_zone_display_name: "Overlay-TZ"
        tier1_id: "ANS-Client-T1"
        advanced_config:
          connectivity: "ON"
        subnets:
          - gateway_address: "192.40.50.1/24"
