# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: localhost
  become: yes
  vars:
      nsx_manager: '10.114.200.41'
      nsx_username: 'admin'
      nsx_password: 'myPassword1!myPassword1!'
      validate_certs: 'false'
  tasks:
    - name: Group ANS-all-vms
      nsxt_policy_group:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-all-vms"
        domain_id: "default"
        expression:
          - resource_type: "Condition"
            member_type: "VirtualMachine"
            key: "Tag"
            operator: "EQUALS"
            value: "nsx"

    - name: Group ANS-web-vms
      nsxt_policy_group:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-web-vms"
        domain_id: "default"
        expression:
          - resource_type: "Condition"
            member_type: "VirtualMachine"
            key: "Tag"
            operator: "EQUALS"
            value: "web"

    - name: Group ANS-app-vms
      nsxt_policy_group:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-app-vms"
        domain_id: "default"
        expression:
          - resource_type: "Condition"
            member_type: "VirtualMachine"
            key: "Tag"
            operator: "EQUALS"
            value: "app"

    - name: Group ANS-db-vms
      nsxt_policy_group:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-db-vms"
        domain_id: "default"
        expression:
          - resource_type: "Condition"
            member_type: "VirtualMachine"
            key: "Tag"
            operator: "EQUALS"
            value: "db"
