# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: localhost
  become: yes
  vars:
      nsx_manager: '10.114.200.41'
      nsx_username: 'admin'
      nsx_password: 'myPassword1!myPassword1!'
      validate_certs: 'false'
  tasks:
    - name: Tier0 ANS-3Tier-T0
      nsxt_policy_tier0:
        hostname: "{{ nsx_manager }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "ANS-3Tier-T0"
        ha_mode: "ACTIVE_STANDBY"
